### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by purp0s3** [Paisseon/KatawaShoujo#1]
I didn't know where else I could send you a message and I thought this might work.

There's no issues, I wanted to thank you for everything you've done for the jailbreak community.

The day I noticed you had an iOS Katawa Shoujo port it clicked me (we might be the only 2 people on earth who share those 2 things in common).

The day I saw your website another click, now I was going through Satella's rootless preferences and saw that poem.

We'll find purpose. Your work helped lots of people. Thank you.

**Comment by Paisseon** [comment]
😊
